language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
script:
  - npm test
  - npm install . -g
  - ./runTests.sh
before_install:
  - npm install -g npm
  - sudo apt-get update -qq
  - sudo apt-get install default-jre
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f3499197be7208e15199
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false