language: node_js
node_js:
  - "iojs"
  - "0.12"
  - "0.10"
  - "0.8"
script:
  - npm test
  - sudo npm install . -g
before_install:
  - sudo npm install -g npm
  - sudo apt-get update -qq
  - sudo apt-get install default-jre
