language: node_js
node_js:
  - "iojs"
  - "0.12"
  - "0.10"
  - "0.8"
script:
  - npm test
  - npm install . -g
  - ./runTests.sh
before_install:
  - npm install -g npm
  - sudo apt-get update -qq
  - sudo apt-get install default-jre
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
